// Generated by `npm run images` — intrinsic sizes so next/image avoids layout shift.
export const images: Record<string, { width: number; height: number }> = {
  "/img/dance-course-proto.webp": {
    "width": 1400,
    "height": 816
  },
  "/img/dance-course-wf.webp": {
    "width": 1400,
    "height": 788
  },
  "/img/dance-home-proto.webp": {
    "width": 1400,
    "height": 816
  },
  "/img/dance-home-wf.webp": {
    "width": 1400,
    "height": 788
  },
  "/img/dance-persona-ingrid.webp": {
    "width": 1400,
    "height": 2318
  },
  "/img/dance-persona-max.webp": {
    "width": 1400,
    "height": 2318
  },
  "/img/dance-reg-proto.webp": {
    "width": 1400,
    "height": 816
  },
  "/img/dance-reg-wf.webp": {
    "width": 1400,
    "height": 788
  },
  "/img/lang-flow.gif": {
    "width": 750,
    "height": 1334
  },
  "/img/lang-home-proto.webp": {
    "width": 984,
    "height": 1934
  },
  "/img/lang-home-wf.webp": {
    "width": 856,
    "height": 1852
  },
  "/img/lang-persona-jiyun.webp": {
    "width": 1400,
    "height": 2318
  },
  "/img/lang-persona-manuel.webp": {
    "width": 1400,
    "height": 2318
  },
  "/img/lang-profile-proto.webp": {
    "width": 984,
    "height": 1934
  },
  "/img/lang-profile-wf.webp": {
    "width": 856,
    "height": 1852
  },
  "/img/lang-test-proto.webp": {
    "width": 984,
    "height": 1934
  },
  "/img/lang-test-wf.webp": {
    "width": 856,
    "height": 1852
  },
  "/img/profile.webp": {
    "width": 1400,
    "height": 1316
  },
  "/img/proj-auth.webp": {
    "width": 1400,
    "height": 691
  },
  "/img/proj-happy-thoughts.webp": {
    "width": 1400,
    "height": 702
  },
  "/img/proj-nutrition.webp": {
    "width": 1244,
    "height": 662
  },
  "/img/proj-organizer.webp": {
    "width": 1400,
    "height": 822
  },
  "/img/proj-quiz.webp": {
    "width": 1110,
    "height": 632
  }
};

export const size = (src: string) => images[src] ?? { width: 1200, height: 800 };
