// Drop source images (png/jpg/svg/webp) into /assets, run `npm run images`.
// Writes optimised WebP files to /public/img and regenerates src/content/images.ts.
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const root = path.resolve(import.meta.dirname, "..");
const assets = path.join(root, "assets");
const out = path.join(root, "public", "img");

if (existsSync(assets)) {
  for (const file of readdirSync(assets).filter((f) => /\.(png|jpe?g|svg|webp)$/i.test(f))) {
    const target = path.join(out, file.replace(/\.\w+$/, ".webp"));
    await sharp(path.join(assets, file), { density: file.endsWith(".svg") ? 144 : 72, limitInputPixels: false })
      .resize({ width: 1600, withoutEnlargement: true })
      .webp({ quality: 82 })
      .toFile(target);
    console.log("→", path.relative(root, target));
  }
}

const manifest = {};
for (const file of readdirSync(out).filter((f) => /\.(webp|gif|png|jpe?g)$/i.test(f)).sort()) {
  const { width, height, pageHeight } = await sharp(path.join(out, file)).metadata();
  manifest[`/img/${file}`] = { width, height: pageHeight ?? height };
}
writeFileSync(
  path.join(root, "src", "content", "images.ts"),
  `// Generated by \`npm run images\` — intrinsic sizes so next/image avoids layout shift.\n` +
    `export const images: Record<string, { width: number; height: number }> = ${JSON.stringify(manifest, null, 2)};\n\n` +
    `export const size = (src: string) => images[src] ?? { width: 1200, height: 800 };\n`,
);
console.log(`✓ ${Object.keys(manifest).length} images in manifest`);
